frr version 9.0
frr defaults traditional
hostname r3
log syslog informational
!
interface lo
 ip address 3.3.3.3/32
 ip router isis main
!
interface eth1
 ip address 10.0.23.2/30
 mpls enable
 ip router isis main
 isis circuit-type level-2-only
 isis network point-to-point
!
interface eth2
 ip address 10.0.34.1/30
 mpls enable
 ip router isis main
 isis circuit-type level-2-only
 isis network point-to-point
!
router isis main
 net 49.0001.0300.0300.0003.00
 is-type level-2-only
 metric-style wide
 mpls-te on
 mpls-te router-address 3.3.3.3
!
mpls ldp
 router-id 3.3.3.3
 !
 address-family ipv4
  discovery transport-address 3.3.3.3
  !
  interface eth1
  interface eth2
 !
!
