frr version 9.0
frr defaults traditional
hostname r1
log syslog informational
!
interface lo
 ip address 1.1.1.1/32
!
interface eth1
 ip address 10.0.1.1/30
 mpls enable
!
interface eth2
 ip address 10.0.12.1/30
 mpls enable
!
interface eth3
 ip address 10.0.41.2/30
 mpls enable
!
router isis main
 net 49.0001.0100.0100.0001.00
 is-type level-2-only
 metric-style wide
 mpls-te on
 mpls-te router-address 1.1.1.1
 !
 interface lo
  passive
 !
 interface eth1
  isis circuit-type level-2-only
  isis network point-to-point
 !
 interface eth2
  isis circuit-type level-2-only
  isis network point-to-point
 !
 interface eth3
  isis circuit-type level-2-only
  isis network point-to-point
!
mpls ldp
 router-id 1.1.1.1
 !
 address-family ipv4
  discovery transport-address 1.1.1.1
  !
  interface eth1
  !
  interface eth2
  !
  interface eth3
 !
!
