frr version 9.0
frr defaults traditional
hostname r2
log syslog informational
!
interface lo
 ip address 2.2.2.2/32
 ip router isis main
!
interface eth1
 ip address 10.0.12.2/30
 mpls enable
 ip router isis main
 isis circuit-type level-2-only
 isis network point-to-point
!
interface eth2
 ip address 10.0.23.1/30
 mpls enable
 ip router isis main
 isis circuit-type level-2-only
 isis network point-to-point
!
interface eth3
 ip address 10.0.2.1/30
 mpls enable
 ip router isis main
 isis circuit-type level-2-only
 isis network point-to-point
!
router isis main
 net 49.0001.0200.0200.0002.00
 is-type level-2-only
 metric-style wide
 mpls-te on
 mpls-te router-address 2.2.2.2
!
mpls ldp
 router-id 2.2.2.2
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth1
  interface eth2
  interface eth3
 !
!
